import type {
  FileMakerConnection,
  Database,
  TableMetadata,
  Webhook,
  WebhookCreateParams,
  FieldMetadata,
} from '@/types/filemaker'

class FileMakerService {
  private connection: FileMakerConnection | null = null

  setConnection(connection: FileMakerConnection) {
    this.connection = connection
  }

  getConnection(): FileMakerConnection | null {
    return this.connection
  }

  private getAuthHeader(): string {
    if (!this.connection) {
      throw new Error('No connection configured')
    }
    return 'Basic ' + btoa(`${this.connection.username}:${this.connection.password}`)
  }

  private getBaseUrl(database?: string): string {
    if (!this.connection) {
      throw new Error('No connection configured')
    }
    const baseUrl = `https://${this.connection.host}/fmi/odata/v4`
    return database ? `${baseUrl}/${database}` : baseUrl
  }

  async testConnection(): Promise<boolean> {
    try {
      await this.getDatabases()
      return true
    } catch (error) {
      console.error('Connection test failed:', error)
      throw error
    }
  }

  async getDatabases(): Promise<Database[]> {
    try {
      const url = this.getBaseUrl()
      console.log('Fetching databases from:', url)

      const response = await fetch(url, {
        headers: {
          'Authorization': this.getAuthHeader(),
        },
      })

      console.log('Response status:', response.status, response.statusText)

      if (!response.ok) {
        const errorText = await response.text()
        console.error('Error response:', errorText)

        if (response.status === 401) {
          throw new Error('Authentication failed. Check your username and password.')
        } else if (response.status === 404) {
          throw new Error('OData API not found. Ensure FileMaker Server 22.0.4+ with OData enabled.')
        } else if (response.status === 0) {
          throw new Error('Network error. Check server host and CORS settings.')
        }

        throw new Error(`Failed to fetch databases: ${response.status} ${response.statusText}`)
      }

      const data = await response.json()
      return data.value || []
    } catch (error) {
      if (error instanceof TypeError && error.message.includes('fetch')) {
        throw new Error(`Cannot reach server at ${this.connection?.host}. Check the hostname and ensure the server is running.`)
      }
      throw error
    }
  }

  async getMetadata(database: string): Promise<TableMetadata[]> {
    const response = await fetch(`${this.getBaseUrl(database)}/$metadata`, {
      headers: {
        'Authorization': this.getAuthHeader(),
      },
    })

    if (!response.ok) {
      throw new Error(`Failed to fetch metadata: ${response.statusText}`)
    }

    const xmlText = await response.text()
    return this.parseMetadataXml(xmlText)
  }

  private parseMetadataXml(xmlText: string): TableMetadata[] {
    const parser = new DOMParser()
    const xmlDoc = parser.parseFromString(xmlText, 'text/xml')
    const tables: TableMetadata[] = []

    const entityTypes = xmlDoc.getElementsByTagName('EntityType')
    for (let i = 0; i < entityTypes.length; i++) {
      const entityType = entityTypes[i]
      const tableName = entityType.getAttribute('Name')
      if (!tableName) continue

      const fields: FieldMetadata[] = []
      const properties = entityType.getElementsByTagName('Property')

      for (let j = 0; j < properties.length; j++) {
        const prop = properties[j]
        const fieldName = prop.getAttribute('Name')
        const fieldType = prop.getAttribute('Type')

        if (!fieldName || !fieldType) continue

        fields.push({
          name: fieldName,
          type: fieldType,
          fieldId: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'FieldID') || undefined,
          tableId: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'TableID') || undefined,
          autoGenerated: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'AutoGenerated') === 'true',
          global: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'Global') === 'true',
          calculation: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'Calculation') === 'true',
        })
      }

      tables.push({
        name: tableName,
        fields,
      })
    }

    return tables
  }

  async getAllWebhooks(database: string): Promise<Webhook[]> {
    const response = await fetch(`${this.getBaseUrl(database)}/Webhook.GetAll`, {
      method: 'POST',
      headers: {
        'Authorization': this.getAuthHeader(),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({}),
    })

    if (!response.ok) {
      throw new Error(`Failed to fetch webhooks: ${response.statusText}`)
    }

    const data = await response.json()
    return data.value || []
  }

  async createWebhook(database: string, params: WebhookCreateParams): Promise<Webhook> {
    const response = await fetch(`${this.getBaseUrl(database)}/Webhook.Add`, {
      method: 'POST',
      headers: {
        'Authorization': this.getAuthHeader(),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(params),
    })

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`Failed to create webhook: ${response.statusText} - ${errorText}`)
    }

    const data = await response.json()
    return data
  }

  async deleteWebhook(database: string, webhookId: string): Promise<void> {
    const response = await fetch(`${this.getBaseUrl(database)}/Webhook.Delete`, {
      method: 'POST',
      headers: {
        'Authorization': this.getAuthHeader(),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ id: webhookId }),
    })

    if (!response.ok) {
      throw new Error(`Failed to delete webhook: ${response.statusText}`)
    }
  }

  async invokeWebhook(database: string, webhookId: string, rowIds?: string[]): Promise<void> {
    const response = await fetch(`${this.getBaseUrl(database)}/Webhook.Invoke`, {
      method: 'POST',
      headers: {
        'Authorization': this.getAuthHeader(),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        id: webhookId,
        ...(rowIds && { rowIds }),
      }),
    })

    if (!response.ok) {
      throw new Error(`Failed to invoke webhook: ${response.statusText}`)
    }
  }

  async executeScript(database: string, scriptName: string, parameter?: string | number | object): Promise<any> {
    const response = await fetch(`${this.getBaseUrl(database)}/Script.${scriptName}`, {
      method: 'POST',
      headers: {
        'Authorization': this.getAuthHeader(),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        scriptParameterValue: parameter,
      }),
    })

    if (!response.ok) {
      throw new Error(`Failed to execute script: ${response.statusText}`)
    }

    return await response.json()
  }
}

export const fileMakerService = new FileMakerService()
