
import type {
  FileMakerConnection,
  Database,
  TableMetadata,
  Webhook,
  WebhookCreateParams,
  FieldMetadata,
} from '@/types/filemaker'
import { webhookTracker } from './webhookTracker'

class FileMakerService {
  private connection: FileMakerConnection | null = null

  setConnection(connection: FileMakerConnection) {
    this.connection = connection
  }

  getConnection(): FileMakerConnection | null {
    return this.connection
  }

  private getAuthHeader(): string {
    if (!this.connection) {
      throw new Error('No connection configured')
    }
    return 'Basic ' + btoa(`${this.connection.username}:${this.connection.password}`)
  }

  private getBaseUrl(database?: string): string {
    if (!this.connection) {
      throw new Error('No connection configured')
    }
    // In development, use relative URL to go through Vite proxy
    // In production, use direct URL
    const isDev = import.meta.env.DEV
    const baseUrl = isDev 
      ? `/fmi/odata/v4`  // Will be proxied to https://192.168.0.24/fmi/odata/v4
      : `https://${this.connection.host}/fmi/odata/v4`
    return database ? `${baseUrl}/${database}` : baseUrl
  }


  async testConnection(): Promise<boolean> {
    try {
      await this.getDatabases()
      return true
    } catch (error) {
      console.error('Connection test failed:', error)
      throw error
    }
  }

  async getDatabases(): Promise<Database[]> {
    try {
      const url = this.getBaseUrl()
      console.log('Fetching databases from:', url)

      const response = await fetch(url, {
        headers: {
          'Authorization': this.getAuthHeader(),
        },
      })

      console.log('Response status:', response.status, response.statusText)

      if (!response.ok) {
        const errorText = await response.text()
        console.error('Error response:', errorText)

        if (response.status === 401) {
          throw new Error('Authentication failed. Check your username and password.')
        } else if (response.status === 404) {
          throw new Error('OData API not found. Ensure FileMaker Server 22.0.4+ with OData enabled.')
        } else if (response.status === 0) {
          throw new Error('Network error. Check server host and ensure SSL certificate is accepted.')
        }

        throw new Error(`Failed to fetch databases: ${response.status} ${response.statusText}`)
      }

      const data = await response.json()
      return data.value || []
    } catch (error) {
      if (error instanceof TypeError && error.message.includes('fetch')) {
        throw new Error(
          `Cannot reach server at ${this.connection?.host}. This may be due to:\n` +
          `1. SSL Certificate Error: Visit https://${this.connection?.host}/fmi/odata/v4 in your browser and accept the certificate warning\n` +
          `2. Server not running or wrong hostname\n` +
          `3. SSL Certificate not accepted: Visit https://${this.connection?.host}/fmi/odata/v4 in your browser and accept the certificate warning\n\n` +
          `Error details: ${error.message}`
        )
      }
      throw error
    }
  }

  async getMetadata(database: string): Promise<TableMetadata[]> {
    const url = `${this.getBaseUrl(database)}/$metadata`
    const response = await fetch(url, {
      headers: {
        'Authorization': this.getAuthHeader(),
      },
    })

    if (!response.ok) {
      throw new Error(`Failed to fetch metadata: ${response.statusText}`)
    }

    const xmlText = await response.text()
    return this.parseMetadataXml(xmlText)
  }

  private parseMetadataXml(xmlText: string): TableMetadata[] {
    const parser = new DOMParser()
    const xmlDoc = parser.parseFromString(xmlText, 'text/xml')
    const tables: TableMetadata[] = []

    const entityTypes = xmlDoc.querySelectorAll('EntityType')

    entityTypes.forEach((entityType) => {
      let tableName = entityType.getAttribute('Name')
      if (!tableName) return

      // Remove any trailing underscores and trim whitespace
      tableName = tableName.trim().replace(/_+$/, '')
      if (!tableName) return

      const fields: FieldMetadata[] = []
      const properties = entityType.querySelectorAll('Property')

      properties.forEach((prop) => {
        let fieldName = prop.getAttribute('Name')
        const fieldType = prop.getAttribute('Type')

        if (!fieldName || !fieldType) return

        // Clean field name too
        fieldName = fieldName.trim().replace(/_+$/, '')

        fields.push({
          name: fieldName,
          type: fieldType,
          fieldId: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'FieldID') || undefined,
          tableId: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'TableID') || undefined,
          autoGenerated: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'AutoGenerated') === 'true',
          global: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'Global') === 'true',
          calculation: prop.getAttributeNS('http://www.filemaker.com/fmpdsoresult', 'Calculation') === 'true',
        })
      })

      tables.push({
        name: tableName,
        fields,
      })
    })

    return tables
  }

  async getAllWebhooks(database: string): Promise<Webhook[]> {
    const startTime = Date.now()
    const url = `${this.getBaseUrl(database)}/Webhook.GetAll`
    const requestDetails = {
      method: 'GET',
      headers: {
        'Authorization': this.getAuthHeader(),
      },
    }
    
    console.log('\n=== Webhook.GetAll Request ===')
    console.log(`Sending request to: GET ${url}`)
    console.log('Request headers:', { 'Content-Type': 'application/json' })
    
    const response = await fetch(url, requestDetails)
    const timingMs = Date.now() - startTime

    if (!response.ok) {
      console.error(`Received response: ${response.status} ${response.statusText}`)
      throw new Error(`Failed to fetch webhooks: ${response.statusText}`)
    }

    const data = await response.json()
    console.log(`Received response: ${response.status}`)
    console.log('Response data:', data)
    console.log(`Timing: ${timingMs}ms\n`)
    
    // Transform FileMaker's webhookID to id
    const webhooks = (data.webhooks || []).map((wh: any) => {
      const webhook = {
        ...wh,
        id: String(wh.webhookID),
      }
      console.log(`Webhook object before return:`, webhook)
      if (webhook.pendingOperations && webhook.pendingOperations.length > 0) {
        console.log(`Webhook ${webhook.id} has ${webhook.pendingOperations.length} pending operations:`, webhook.pendingOperations)
      }
      return webhook
    })
    console.log('Final webhooks array:', webhooks)
    return webhooks
  }

  async createWebhook(database: string, params: WebhookCreateParams): Promise<Webhook> {
    const startTime = Date.now()
    const url = `${this.getBaseUrl(database)}/Webhook.Add`
    
    try {
      console.log('\n=== Webhook.Add Request ===')
      console.log(`Sending request to: POST ${url}`)
      console.log('Request body:', params)
      
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Authorization': this.getAuthHeader(),
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(params) || undefined,
      })

      const timingMs = Date.now() - startTime
      const data = await response.json()

      if (!response.ok) {
        const errorText = await response.text()
        console.error(`Received response: ${response.status} ${response.statusText}`)
        console.error('Error details:', errorText)
        webhookTracker.trackError('create', database, `Failed to create webhook: ${response.statusText} - ${errorText}`)
        throw new Error(`Failed to create webhook: ${response.statusText} - ${errorText}`)
      }

      console.log(`Received response: ${response.status}`)
      console.log('Response data:', data)
      console.log(`Timing: ${timingMs}ms\n`)

      // FileMaker only returns webhookID, so we need to construct the full webhook object
      // from the parameters we sent
      const webhookId = data.webhookResult?.webhookID || data.webhookID
      
      const webhook = {
        id: String(webhookId),
        webhook: params.webhook,
        tableName: params.tableName,
        notifySchemaChanges: params.notifySchemaChanges,
        select: params.select,
        filter: params.filter,
        headers: params.headers,
      }

      // Track the creation for analysis
      webhookTracker.trackWebhookCreation(webhook, database, timingMs, data)

      return webhook
    } catch (error) {
      const timingMs = Date.now() - startTime
      webhookTracker.trackError('create', database, error instanceof Error ? error.message : 'Unknown error')
      throw error
    }
  }

  async updateWebhook(database: string, webhookId: string, params: WebhookCreateParams): Promise<{ webhook: Webhook; oldId: string }> {
    // FileMaker OData only supports: Add, Delete, Get, GetAll, Invoke
    // No native update operation exists, so we must delete and recreate
    // NOTE: This changes the webhook ID - FileMaker generates new sequential IDs
    // This means any external system referencing the old ID will break
    const oldId = webhookId
    const startTime = Date.now()
    
    try {
      await this.deleteWebhook(database, webhookId)
      const newWebhook = await this.createWebhook(database, params)
      const timingMs = Date.now() - startTime
      
      // Track the update for analysis
      webhookTracker.trackWebhookUpdate(oldId, newWebhook, database, timingMs)
      
      return { webhook: newWebhook, oldId }
    } catch (error) {
      const timingMs = Date.now() - startTime
      webhookTracker.trackError('update', database, error instanceof Error ? error.message : 'Unknown error', webhookId)
      throw error
    }
  }

  async deleteWebhook(database: string, webhookId: string): Promise<void> {
    const startTime = Date.now()
    const url = `${this.getBaseUrl(database)}/Webhook.Delete(${webhookId})`
    
    try {
      console.log('\n=== Webhook.Delete Request ===')
      console.log(`Sending request to: POST ${url}`)
      console.log('Request body:', { webhookId })
      
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Authorization': this.getAuthHeader(),
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({}),
      })

      const timingMs = Date.now() - startTime

      if (!response.ok) {
        const errorText = await response.text()
        console.error(`Received response: ${response.status} ${response.statusText}`)
        console.error('Error details:', errorText)
        webhookTracker.trackError('delete', database, `Failed to delete webhook: ${response.statusText} - ${errorText}`, webhookId)
        throw new Error(`Failed to delete webhook: ${response.statusText}`)
      }

      console.log(`Received response: ${response.status}`)
      console.log(`Timing: ${timingMs}ms\n`)
      
      // Track the deletion for analysis
      webhookTracker.trackWebhookDeletion(webhookId, database, timingMs)
    } catch (error) {
      const timingMs = Date.now() - startTime
      webhookTracker.trackError('delete', database, error instanceof Error ? error.message : 'Unknown error', webhookId)
      throw error
    }
  }

  async invokeWebhook(database: string, webhookId: string, tableName?: string): Promise<void> {
    const startTime = Date.now()
    let rowIds: number[] = []

    // If tableName is provided, fetch sample record IDs from that table
    if (tableName) {
      try {
        const baseUrl = `${this.getBaseUrl(database)}/${tableName}`
        const queryString = `$select="id"&$top=5`
        const fullUrl = `${baseUrl}?${queryString}`
        const response = await fetch(fullUrl, {
          headers: {
            'Authorization': this.getAuthHeader(),
          },
        })

        if (response.ok) {
          const data = await response.json()
          // Extract record IDs from the response
          if (data.value && Array.isArray(data.value)) {
            rowIds = data.value.map((record: any) => record.id).filter((id: any) => id !== undefined)
          }
        }
      } catch (err) {
        console.warn('Failed to fetch record IDs, using default:', err)
      }
    }

    // If we couldn't fetch any IDs, use a default
    if (rowIds.length === 0) {
      rowIds = [1]
    }

    const url = `${this.getBaseUrl(database)}/Webhook.Invoke(${webhookId})`
    const bodyPayload = { rowIDs: rowIds }
    const bodyString = JSON.stringify(bodyPayload)
    
    console.log('\n=== Webhook.Invoke Request ===')
    console.log(`Sending request to: POST ${url}`)
    console.log('Request body:', bodyPayload)
    
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Authorization': this.getAuthHeader(),
        'Content-Type': 'application/json',
      },
      body: bodyString,
    }
    
    const response = await fetch(url, fetchOptions)
    const timingMs = Date.now() - startTime

    if (!response.ok) {
      const errorText = await response.text()
      console.error(`Received response: ${response.status} ${response.statusText}`)
      console.error('Error details:', errorText)
      throw new Error(`Failed to invoke webhook: ${response.statusText} - ${errorText}`)
    }
    
    console.log(`Received response: ${response.status}`)
    console.log(`Timing: ${timingMs}ms\n`)
  }

  async executeScript(database: string, scriptName: string, parameter?: string | number | object): Promise<any> {
    const url = `${this.getBaseUrl(database)}/Script.${scriptName}`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': this.getAuthHeader(),
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        scriptParameterValue: parameter,
      }) || undefined,
    })

    if (!response.ok) {
      throw new Error(`Failed to execute script: ${response.statusText}`)
    }

    return await response.json()
  }
}

export const fileMakerService = new FileMakerService()
