export interface FileMakerConnection {
  host: string
  username: string
  password: string
}

export interface Database {
  name: string
}

export interface FieldMetadata {
  name: string
  type: string
  fieldId?: string
  tableId?: string
  autoGenerated?: boolean
  global?: boolean
  calculation?: boolean
}

export interface TableMetadata {
  name: string
  fields: FieldMetadata[]
}

export interface PendingOperation {
  operation: 'ADD' | 'UPDATE' | 'DELETE' | 'SCHEMA'
  rowIDs: number[]
  status: 'NOT_SENT' | 'SENT' | 'FAILED'
  lastErrorCode: number
  lastErrorMessage: string
  sendAttempts: number
}

export interface Webhook {
  id: string
  webhook: string
  headers?: Record<string, string>
  tableName: string
  notifySchemaChanges: boolean
  select?: string
  filter?: string
  pendingOperations?: PendingOperation[]
  deleted?: boolean // Flag to mark webhooks as deleted (soft delete)
}

export interface WebhookCreateParams {
  webhook: string
  headers?: Record<string, string>
  tableName: string
  notifySchemaChanges: boolean
  select?: string
  filter?: string
}

export interface ScriptResult {
  code: number
  resultParameter: string
}

export interface ScriptResponse {
  scriptResult: ScriptResult
}
